#!/usr/bin/env python
# -*- coding: UTF-8 -*-

"""
Project: Master Chef
Стоковые константы (для ГУИ/локализации)
"""

Str_Menu_Welcome = u"Welcome, "
Str_Menu_PlayCareer = "P L A Y"
Str_Menu_PlayEndless = "PLAY ENDLESS"
Str_Menu_Players = "Click to change player"
Str_Menu_Options = "Options"
Str_Menu_Rules = "Help"
Str_Menu_Cookbook = "Cookbook"
Str_Menu_Hiscores = "Hiscores"
Str_Menu_Quit = "Quit"

Str_HelpPrev = "Page down"
Str_HelpNext = "Page up"
Str_HelpClose = "Close window"

Str_Players_Title = "PLAY AS..."
Str_Players_Create = "Create new player"
Str_PlayersRemove = "Remove player"
Str_PlayersOk = "Ok"
Str_PlayersCancel = "Cancel"
Str_PlayersNew = "Create new player"

Str_EnterName_Title = "Please enter your name"
Str_EnterNameOk = "Ok"
Str_EnterNameCancel = "Cancel"
Str_EnterName_Error_Empty = u"Cannot use empty name"
Str_EnterName_Error_Bad = u"Bad name"
Str_EnterName_Error_Exist = u"This name already exists"

Str_LvGoalsPlay = u"PLAY"
Str_LvGoals_Title = "Level "

Str_LvComplete_Title = "LEVEL RESULTS"
Str_LvCompleteRestart = "Try again"
Str_LvCompleteNextLevel = "Continue"
Str_LvCompleteTryAgain = "Try again"
Str_LvCompleteMainMenu = "Exit to menu"
Str_LvComplete_Served = "Customers served: "
Str_LvComplete_Lost = "Customers lost: "
Str_LvComplete_Score = "Money earned: "
Str_LvComplete_Expert = "Expert score! "
Str_LvComplete_Hiscore = "Best score! "
Str_LvComplete_BestScore = "Best score: "
Str_LvComplete_AchievedBy = "Achieved by: "
Str_LvComplete_TooLate = "You are too late!\nRestart the level?"
Str_LvComplete_Passed = "You have passed level "

Str_EpiCompleteNext = "Continue quest"
Str_EpiCompleteMainMenu = "Exit to main menu"

Str_GameOver_Title = "GAME OVER"
Str_GameOverHiscores = "View hiscores"
Str_GameOverMainMenu = "Exit to main menu"

Str_Options_Title = "OPTIONS"
Str_Options_LabelSound = "Sound volume"
Str_Options_LabelMusic = "Music volume"
Str_Options_LabelMute = "Mute"
Str_Options_LabelHints = "Hints"
Str_Options_LabelFullscreen = "Fullscreen"
Str_OptionsOk = "Ok"
Str_OptionsCancel = "Cancel"
Str_OptionsResume = "Resume"
Str_OptionsRestart = "Restart level"
Str_OptionsEndGame = "Main menu"

Str_Hiscores_Title = "HISCORES"
Str_HiscoresReset = "Reset scores"
Str_HiscoresClose = "Close"

Str_MapStart = "Start game"
Str_MapViewResults = "View results"
Str_MapMainMenu = "Main menu"
Str_MapHiscore = "Hiscore "
Str_MapAchievedBy = " achieved by "
Str_ComicsNext = "NEXT"
Str_IntroCompetitors = "COMPETITORS"
Str_OutroCompetitors = "COMPETITORS"
Str_OutroPoints = "POINTS"
Str_OutroSpeech = "Meet our winners!"
Str_OutroNotPass = "Jenny, play more\n to pass this stage."

Str_Yes = "YES"
Str_No = "NO"
Str_Cancel = "Cancel"

Str_Question_Continue = "Continue last saved game?"
Str_Answer_Continue_Continue = "Continue"
Str_Answer_Continue_NewGame = "New game"
Str_Question_RemovePlayer = "Remove player, are you sure?"
Str_Question_RestartLevel = "Restart level, are you sure?"
Str_Question_ClearHiscores = "Clear hiscores list, are you sure?"

Str_HUD_RestaurantClosed = "CLOSED"
Str_HUD_MenuButton = "MENU"
Str_HUD_LevelText = "LEVEL"
Str_HUD_ScoreText = "SCORE"
Str_HUD_GoalText = "GOAL"
Str_HUD_ExpertText = "EXPERT"
Str_HUD_ApprovalText = "BONUS"
Str_HUD_NoPeopleText = "PEOPLE"

